#ifndef __TEGDecTwoBody_h__
#define __TEGDecTwoBody_h__

#include "TEGDecay.h"
#include "TEGDistDsigDOmega.h"

enum{EW=0,ECosTheta,EPhi};//random number map


class TEGDecTwoBody : public TEGDecay {

 protected:
  //TEGDistribution* fDist;   //distribution for random nummbers
  //Kinematics to be generated by distribution
  Double_t fCosTheta;
  Double_t fPhi;
  Double_t fW;
  Bool_t fIsWCosTh;
  Bool_t fIsE1Theta1;

 public:
  TEGDecTwoBody( );
  virtual ~TEGDecTwoBody();

  virtual Bool_t GenDecay( );
  virtual Bool_t GenWCosThDecay( ); //calculates final state from W and cos(thetaCM)
  virtual Bool_t GenE1Theta1Decay( ); //calculates final state from E1 and theta1
 //void SetDistribution(TEGDistribution* dist){fDist=dist;}
  void SetDistParticle(TObject* dp){
    //make this particle first in list, thus gets dist costh
    fProducts->Remove(dp);
    fProducts->AddFirst(dp);
  }
  void SetIsWCosTh(){fIsWCosTh=kTRUE;fIsE1Theta1=kFALSE;}
  void SetIsE1Theta1(){fIsWCosTh=kFALSE;fIsE1Theta1=kTRUE;}
  ClassDef(TEGDecTwoBody,1)
};

#endif


