/********************************************************************
* /home/dglazier/Work/clas12/EdGen/src//TEGGenDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/dglazier/Work/clas12/EdGen/src//TEGGenDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTEGGenDict();
extern void G__cpp_setup_inheritanceTEGGenDict();
extern void G__cpp_setup_typetableTEGGenDict();
extern void G__cpp_setup_memvarTEGGenDict();
extern void G__cpp_setup_globalTEGGenDict();
extern void G__cpp_setup_memfuncTEGGenDict();
extern void G__cpp_setup_funcTEGGenDict();
extern void G__set_cpp_environmentTEGGenDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/dglazier/Work/clas12/EdGen/src//TEGDecElElasticRad.h"
#include "/home/dglazier/Work/clas12/EdGen/src//TEGDecTwoBody.h"
#include "/home/dglazier/Work/clas12/EdGen/src//TEGDecay.h"
#include "/home/dglazier/Work/clas12/EdGen/src//TEGDistDsigDOmega.h"
#include "/home/dglazier/Work/clas12/EdGen/src//TEGDistDsigDt.h"
#include "/home/dglazier/Work/clas12/EdGen/src//TEGDistEScat.h"
#include "/home/dglazier/Work/clas12/EdGen/src//TEGDistribution.h"
#include "/home/dglazier/Work/clas12/EdGen/src//TEGElectroReaction.h"
#include "/home/dglazier/Work/clas12/EdGen/src//TEGGenerator.h"
#include "/home/dglazier/Work/clas12/EdGen/src//TEGOutAll.h"
#include "/home/dglazier/Work/clas12/EdGen/src//TEGOutGEMC.h"
#include "/home/dglazier/Work/clas12/EdGen/src//TEGOutLorentz.h"
#include "/home/dglazier/Work/clas12/EdGen/src//TEGOutput.h"
#include "/home/dglazier/Work/clas12/EdGen/src//TEGParticle.h"
#include "/home/dglazier/Work/clas12/EdGen/src//TEGPhotoReaction.h"
#include "/home/dglazier/Work/clas12/EdGen/src//TEGReaction.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TEGGenDictLN_TClass;
extern G__linked_taginfo G__TEGGenDictLN_TBuffer;
extern G__linked_taginfo G__TEGGenDictLN_TMemberInspector;
extern G__linked_taginfo G__TEGGenDictLN_TObject;
extern G__linked_taginfo G__TEGGenDictLN_TNamed;
extern G__linked_taginfo G__TEGGenDictLN_TString;
extern G__linked_taginfo G__TEGGenDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__TEGGenDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TEGGenDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TEGGenDictLN_TObjArray;
extern G__linked_taginfo G__TEGGenDictLN_TClonesArray;
extern G__linked_taginfo G__TEGGenDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TEGGenDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TEGGenDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TEGGenDictLN_TArrayI;
extern G__linked_taginfo G__TEGGenDictLN_TRandom3;
extern G__linked_taginfo G__TEGGenDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TEGGenDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TEGGenDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TEGGenDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TEGGenDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TEGGenDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TEGGenDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TEGGenDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TEGGenDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TEGGenDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TEGGenDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TEGGenDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TEGGenDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TEGGenDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TEGGenDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TEGGenDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TEGGenDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TEGGenDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TEGGenDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TEGGenDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TEGGenDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TEGGenDictLN_TVector3;
extern G__linked_taginfo G__TEGGenDictLN_TLorentzVector;
extern G__linked_taginfo G__TEGGenDictLN_TEGParticle;
extern G__linked_taginfo G__TEGGenDictLN_TEGDistribution;
extern G__linked_taginfo G__TEGGenDictLN_TEGDecay;
extern G__linked_taginfo G__TEGGenDictLN_TF1;
extern G__linked_taginfo G__TEGGenDictLN_TParticlePDG;
extern G__linked_taginfo G__TEGGenDictLN_TDatabasePDG;
extern G__linked_taginfo G__TEGGenDictLN_TEGGenerator;
extern G__linked_taginfo G__TEGGenDictLN_TEGOutput;
extern G__linked_taginfo G__TEGGenDictLN_TArrayD;
extern G__linked_taginfo G__TEGGenDictLN_TF2;
extern G__linked_taginfo G__TEGGenDictLN_TH2;
extern G__linked_taginfo G__TEGGenDictLN_TEGDistDsigDOmega;
extern G__linked_taginfo G__TEGGenDictLN_TEGDecElElasticRad;
extern G__linked_taginfo G__TEGGenDictLN_TEGDecTwoBody;
extern G__linked_taginfo G__TEGGenDictLN_TEGReaction;
extern G__linked_taginfo G__TEGGenDictLN_TEGDistDsigDt;
extern G__linked_taginfo G__TEGGenDictLN_TEGDistEScat;
extern G__linked_taginfo G__TEGGenDictLN_TEGElectroReaction;
extern G__linked_taginfo G__TEGGenDictLN_TFile;
extern G__linked_taginfo G__TEGGenDictLN_TTree;
extern G__linked_taginfo G__TEGGenDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TEGGenDictLN_TEGOutAll;
extern G__linked_taginfo G__TEGGenDictLN_TEGOutGEMC;
extern G__linked_taginfo G__TEGGenDictLN_TEGOutLorentz;
extern G__linked_taginfo G__TEGGenDictLN_TEGPhotoReaction;

/* STUB derived class for protected member access */
